server:
  port: 8080
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    static-path-pattern: /resources/**

  devtools:
    add-properties: true

logging:
  level:
    org.springframework.web: INFO